### ISSUE TITLE
bootstrap.js not able to run for branch mytest1

### ISSUE THREAD

**Issue by rishilaish1819** [rrparty/studyapps#1]
pull branch mytest1 and check the issue...

**Comment by ronscoder** [comment]
Replace bootstrap files (css & js) with the version you want. The version in the repo is v4. I think you want v3. v4 is very different from v3. 
![screen shot 2017-03-22 at 2 17 24 am](https://cloud.githubusercontent.com/assets/7016159/24170103/c47a0af6-0ea5-11e7-8b1b-05cd04248d2d.png)

**Comment by ronscoder** [comment]
I have replaced v4 with v3. 
Run `git pull` and Check if it's working. 

Why don't you directly work on master branch?

**Comment by rishilaish1819** [comment]
recently figure out that angular 2 requires "ng-whatsoevr" attr many a times in HTML tags for configuring business logics..so manipulating these tags while m designing the UI might hamper ur work...require proper coordination i guess. dats y i create a separate branch in remote not to corrupt the original...

**Comment by ronscoder** [comment]
Ok. Let's do like this:
Once you have completed a page/html/template, merge your branch to master - 
`git checkout master`
`git merge <your-branch>`

Then `git checkout <your-branch>` to continue your work on `<your-branch>`

**Comment by rishilaish1819** [comment]
Changed back to bootstrp v4...works fine after replacing bootstrap.min.js with the latest version.
